import block from './block.json';
import item from './item.json';
import Ajv from 'ajv';

const ajv = new Ajv({ allErrors: true })
ajv.addFormat("@autoGenerated", ".*")
ajv.addFormat("@foreignKey", ".*")
ajv.addSchema(block, '/block')
ajv.addSchema(item, '/item')

export default {
  validator: ajv,
  schemas: {
    block: {
      name: 'Block',
      schema: block
    },
    item: {
      name: 'Item',
      schema: item
    }
  }
}
