<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <Compile Include="../../../moorestech_server/Assets/Scripts/Game.BeltSegment/**/*.cs" />
    <Compile Include="../../../moorestech_server/Assets/Scripts/Tests/UnitTest/Game/BeltSegment/*.cs" />
  </ItemGroup>
</Project>
