# 箱の world.json から観察の起動引数（mapMode・seed）を取り出す。読めない項目は空にし理由を stderr へ全部出す
# Extracts the observation boot arguments (mapMode, seed) from the box's world.json; unreadable fields become empty and every reason goes to stderr
import json, shlex, sys

notes = []
data = {}
# 外部JSONのパースは外部境界。壊れた箱で run 全体を落とさないため例外をここで閉じる
# Parsing external JSON is a boundary; the exception is contained here so a broken box cannot kill the run
try:
    with open(sys.argv[1]) as handle:
        data = json.load(handle)
except Exception as error:
    notes.append("world.json を読めない（%s: %s）。mapMode・seed は空として続行する" % (type(error).__name__, error))
if not isinstance(data, dict):
    notes.append("world.json の中身が辞書でない。mapMode・seed は空として続行する")
    data = {}

# mapMode は綴りをそのまま渡す。生成ワールドの判定は完全一致（WorldMapMode.IsGenerated と同じ）で呼び出し側が行う
# mapMode is passed verbatim; the caller judges generated by the exact spelling, as WorldMapMode.IsGenerated does
map_mode = data.get("mapMode")
if not isinstance(map_mode, str):
    notes.append("world.json に mapMode が無い/文字列でない。空として続行する")
    map_mode = ""
seed = data.get("seed")
if isinstance(seed, int) and not isinstance(seed, bool):
    seed = str(seed)
else:
    notes.append("world.json に seed が無い/整数でない（%r）。空として続行する" % (seed,))
    seed = ""

for note in notes:
    sys.stderr.write("[prepare] %s\n" % note)
print("WORLD_MAP_MODE=%s" % shlex.quote(map_mode))
print("WORLD_SEED=%s" % shlex.quote(seed))
