using System.Text;
using Mooresmaster.LocalizationCsv;

namespace mooresmaster.Generator.Localization;

public static class LocalizationCodeGenerator
{
    public static string Generate(LocalizationCsv csv)
    {
        LocalizationCodeSyntax.ValidateKeys(csv);
        var builder = new StringBuilder();

        // 生成物の共通宣言とキー・辞書テーブルを順番に構築する
        // Build shared declarations, keys, and dictionary tables in order
        builder.AppendLine("// <auto-generated by LocalizationSourceGenerator />");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.AppendLine("namespace Mooresmaster.Localization.Generated");
        builder.AppendLine("{");
        EmitKeyType(builder);
        EmitKeys(builder, LocalizationKeyTree.Build(csv.Rows));
        EmitTable(builder, csv);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitKeyType(StringBuilder builder)
    {
        builder.AppendLine("    public readonly struct LocalizationKey");
        builder.AppendLine("    {");
        builder.AppendLine("        public readonly string Key;");
        builder.AppendLine("        public LocalizationKey(string key) { Key = key; }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitKeys(StringBuilder builder, LocalizationKeyNode root)
    {
        builder.AppendLine("    public static class LocalizationKeys");
        builder.AppendLine("    {");
        foreach (var child in root.Children)
        {
            EmitNode(child, 2);
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        #region Internal

        void EmitNode(LocalizationKeyNode node, int depth)
        {
            var indent = new string(' ', depth * 4);
            if (node.IsLeaf)
            {
                builder.AppendLine(
                    $"{indent}public static readonly LocalizationKey {LocalizationCodeSyntax.ToPascalCase(node.Segment)} = new LocalizationKey(\"{LocalizationCodeSyntax.Escape(node.FullKey)}\");");
                return;
            }

            // 枝ノードは静的クラスとして深さ優先で展開する
            // Expand branch nodes depth-first as static classes
            builder.AppendLine($"{indent}public static class {LocalizationCodeSyntax.ToPascalCase(node.Segment)}");
            builder.AppendLine($"{indent}{{");
            foreach (var child in node.Children)
            {
                EmitNode(child, depth + 1);
            }

            builder.AppendLine($"{indent}}}");
        }

        #endregion
    }

    private static void EmitTable(StringBuilder builder, LocalizationCsv csv)
    {
        builder.AppendLine("    public static class VanillaLocalizationTable");
        builder.AppendLine("    {");
        EmitLanguageCodes(builder, csv.LanguageCodes);
        builder.AppendLine("        private static readonly Dictionary<string, IReadOnlyDictionary<string, string>> Languages = BuildLanguages();");
        builder.AppendLine("        public static readonly IReadOnlyDictionary<string, string> SourceTexts = BuildSourceTexts();");
        builder.AppendLine();

        // 言語検索は成功時の辞書と失敗時のnullを明示する
        // Return the language dictionary on success and null on failure
        builder.AppendLine("        public static bool TryGetLanguage(string code, out IReadOnlyDictionary<string, string> dictionary)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (Languages.TryGetValue(code, out dictionary))");
        builder.AppendLine("            {");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            dictionary = null;");
        builder.AppendLine("            return false;");
        builder.AppendLine("        }");
        builder.AppendLine();
        EmitBuildLanguages(builder, csv);
        EmitBuildSourceTexts(builder, csv.Rows);
        builder.AppendLine("    }");
    }

    private static void EmitLanguageCodes(StringBuilder builder, string[] languageCodes)
    {
        builder.Append("        public static readonly string[] LanguageCodes = new string[] { ");
        for (var index = 0; index < languageCodes.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            builder.Append($"\"{LocalizationCodeSyntax.Escape(languageCodes[index])}\"");
        }

        builder.AppendLine(" };");
    }

    private static void EmitBuildLanguages(StringBuilder builder, LocalizationCsv csv)
    {
        builder.AppendLine("        private static Dictionary<string, IReadOnlyDictionary<string, string>> BuildLanguages()");
        builder.AppendLine("        {");
        builder.AppendLine("            var languages = new Dictionary<string, IReadOnlyDictionary<string, string>>();");
        for (var languageIndex = 0; languageIndex < csv.LanguageCodes.Length; languageIndex++)
        {
            // ブロックスコープごとに言語辞書を生成して登録する
            // Build and register one language dictionary per block scope
            builder.AppendLine("            {");
            builder.AppendLine("                var texts = new Dictionary<string, string>();");
            foreach (var row in csv.Rows)
            {
                builder.AppendLine(
                    $"                texts[\"{LocalizationCodeSyntax.Escape(row.Key)}\"] = \"{LocalizationCodeSyntax.Escape(row.Texts[languageIndex])}\";");
            }

            builder.AppendLine($"                languages[\"{LocalizationCodeSyntax.Escape(csv.LanguageCodes[languageIndex])}\"] = texts;");
            builder.AppendLine("            }");
        }

        builder.AppendLine("            return languages;");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void EmitBuildSourceTexts(StringBuilder builder, LocalizationRow[] rows)
    {
        builder.AppendLine("        private static IReadOnlyDictionary<string, string> BuildSourceTexts()");
        builder.AppendLine("        {");
        builder.AppendLine("            var sourceTexts = new Dictionary<string, string>();");
        foreach (var row in rows)
        {
            builder.AppendLine($"            sourceTexts[\"{LocalizationCodeSyntax.Escape(row.Key)}\"] = \"{LocalizationCodeSyntax.Escape(row.Source)}\";");
        }

        builder.AppendLine("            return sourceTexts;");
        builder.AppendLine("        }");
    }

}
