// チュートリアルアンカーIDの単一ソース。静的ID一覧と動的IDのprefixをここでのみ定義する
// Single source of truth for tutorial anchor IDs; static IDs and dynamic ID prefixes live only here

export const TutorialAnchorIds = {
  placementHud: "placement.hud",
  deleteHud: "delete.hud",
  gameCrosshair: "game.crosshair",
  trainHudStatus: "train-hud.status",
  pauseMenu: "pause.menu",
  pauseSave: "pause.save",
  pauseBack: "pause.back",
  inventoryCloseButton: "inventory.close-button",
  challengeCurrentHud: "challenge.current-hud",
  recipeCraftButton: "recipe.craft-button",
  miningHud: "mining.hud",
  challengePanel: "challenge.panel",
  challengeCategories: "challenge.categories",
  hotbarHud: "hotbar.hud",
} as const;

export type StaticTutorialAnchorId = (typeof TutorialAnchorIds)[keyof typeof TutorialAnchorIds];

// 動的アンカーIDのprefix。マスタデータはこの書式のanchorIdを直書きする（recipeItemのみUnity側FromItemIdが生成）
// Dynamic anchor ID prefixes; master data writes anchor IDs in these forms directly (only recipeItem is generated by Unity's FromItemId)
export const TutorialAnchorDynamicPrefixes = {
  researchNode: "research.node-",
  recipeItem: "recipe.item-",
  buildMenuEntry: "build-menu.entry-",
  challengeNode: "challenge.node-",
} as const;

export type DynamicTutorialAnchorId =
  `${(typeof TutorialAnchorDynamicPrefixes)[keyof typeof TutorialAnchorDynamicPrefixes]}${string}`;

export function researchNodeAnchorId(guid: string): DynamicTutorialAnchorId {
  return `${TutorialAnchorDynamicPrefixes.researchNode}${guid}`.toLowerCase() as DynamicTutorialAnchorId;
}

export function recipeItemAnchorId(itemId: number): DynamicTutorialAnchorId {
  return `${TutorialAnchorDynamicPrefixes.recipeItem}${itemId}` as DynamicTutorialAnchorId;
}

export function buildMenuEntryAnchorId(kind: string, id: string): DynamicTutorialAnchorId {
  return `${TutorialAnchorDynamicPrefixes.buildMenuEntry}${kind}-${id}`.toLowerCase() as DynamicTutorialAnchorId;
}

export function challengeNodeAnchorId(guid: string): DynamicTutorialAnchorId {
  return `${TutorialAnchorDynamicPrefixes.challengeNode}${guid}`.toLowerCase() as DynamicTutorialAnchorId;
}
