//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Asset/Common/moorestechInputSettings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MoorestechInputSettings: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MoorestechInputSettings()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""moorestechInputSettings"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f62a4b92-ef5e-4175-8f4c-c9075429d32c"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6bc1aaf4-b110-4ff7-891e-5b9fe6f32c4d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""2690c379-f54d-45be-a724-414123833eb4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8c4abdf8-4099-493a-aa1a-129acec7c3df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""PassThrough"",
                    ""id"": ""980e881e-182c-404c-8cbf-3d09fdb48fef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""b7594ddb-26c9-4ba2-bd5a-901468929edc"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2063a8b5-6a45-43de-851b-65f3d46e7b58"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""64e4d037-32e1-4fb9-80e4-fc7330404dfe"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0fce8b11-5eab-4e4e-a741-b732e7b20873"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7bdda0d6-57a8-47c8-8238-8aecf3110e47"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bb94b405-58d3-4998-8535-d705c1218a98"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""929d9071-7dd0-4368-9743-6793bb98087e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""28abadba-06ff-4d37-bb70-af2f1e35a3b9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""45f115b6-9b4f-4ba8-b500-b94c93bf7d7e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e2f9aa65-db06-4c5b-a2e9-41bc8acb9517"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed66cbff-2900-4a62-8896-696503cfcd31"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false,invertY=false),ScaleVector2(x=0.5,y=0.5)"",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1d171b6-19d8-47a6-ba3a-71b6a8e7b3c0"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false,invertY=false),StickDeadzone,ScaleVector2(x=300,y=300)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bd55a0b-761e-4ae4-89ae-8ec127e08a29"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f973413-5e27-4239-acee-38c4a63feeba"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc65b89f-9bd3-43fb-92af-d0d87ba5faa4"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8fcd86e-dcfd-4f88-8e93-b638cdbf3320"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Playable"",
            ""id"": ""3b8c937a-e56c-4355-8df4-4b18aebda850"",
            ""actions"": [
                {
                    ""name"": ""ScreenLeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""2daa6d31-e71b-44fb-a02c-1a3022394306"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScreenRightClick"",
                    ""type"": ""Button"",
                    ""id"": ""d5203e91-bd51-4d08-8095-5616e05b4135"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickPosition"",
                    ""type"": ""Value"",
                    ""id"": ""bc0681b1-9b67-4790-9cea-db84f7866f18"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BlockPlaceRotation"",
                    ""type"": ""Button"",
                    ""id"": ""f7d3e6db-d7f7-47fd-89ba-d5aebde59bfd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""40570264-d64b-4fab-8a17-e82a6c84bbb5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ScreenLeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76a36c78-8aec-409f-95fd-d65c19c90c78"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ClickPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d186815-25b5-4945-9b66-e3a062e013dd"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""BlockPlaceRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b87d5855-8a6a-4fa3-993e-b2fd913a9b72"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ScreenRightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""a5b83090-4129-4641-9269-ed030245dfb4"",
            ""actions"": [
                {
                    ""name"": ""OpenMenu"",
                    ""type"": ""Button"",
                    ""id"": ""d05b5bb9-2c20-4891-9da9-7b462f4ac170"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CloseUI"",
                    ""type"": ""Button"",
                    ""id"": ""36b3d4de-bd2d-438c-9e4c-df3e938816ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""17545790-f73d-43a1-8cf7-6a7a14e5f0a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InventoryItemOnePut"",
                    ""type"": ""Button"",
                    ""id"": ""d5b7c844-d220-4349-8215-850781d15821"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""InventoryItemHalve"",
                    ""type"": ""Button"",
                    ""id"": ""4e16a79f-7adf-46ea-912e-883f895d6760"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HotBar"",
                    ""type"": ""Value"",
                    ""id"": ""97c655d1-9252-44a3-82bb-a7f5abd2debd"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchHotBar"",
                    ""type"": ""Value"",
                    ""id"": ""d2f618be-de73-4ef6-a5b9-1b42a7ab7978"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BlockDelete"",
                    ""type"": ""Button"",
                    ""id"": ""c32a2ed0-2d81-426d-84ef-3708b00aa473"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BlockPlace"",
                    ""type"": ""Button"",
                    ""id"": ""d4120381-5129-4f9c-978b-e08cb83b2209"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AllCraft"",
                    ""type"": ""Button"",
                    ""id"": ""8c3efc46-7724-4341-a7e8-9402cddefebf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OneStackCraft"",
                    ""type"": ""Button"",
                    ""id"": ""ed8ecda3-c72b-4262-95fe-d2a5b75d1a64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""QuestUI"",
                    ""type"": ""Button"",
                    ""id"": ""b6e2a7bb-43b9-40de-b975-aace67c3d62e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemDirectMove"",
                    ""type"": ""Button"",
                    ""id"": ""4063cc99-dc31-4a12-8b27-11c6c7eba545"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1541a9fa-f950-453c-bbcd-9a3a24057279"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""InventoryItemOnePut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28f13127-1302-42a6-acf5-88ff169cec76"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""InventoryItemHalve"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a29f8259-bf97-43fc-8ea0-90be9df5ba4b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c032cecf-09c5-4a01-8337-4f455fb210a3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""OpenMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56a2af2c-e73c-4e4c-8634-444c9cfdc0f4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""CloseUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Hot Bar Key Board"",
                    ""id"": ""853740fe-6882-4ac4-8439-4c65c70f4ff7"",
                    ""path"": ""HotBarKeyBoard"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""select0"",
                    ""id"": ""a054cc2f-0784-4063-a585-503df8ea50b7"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select1"",
                    ""id"": ""4a8e5941-13b3-44d5-af35-7b38d53c0f9d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select2"",
                    ""id"": ""7dc8b165-0fb0-4416-a2d8-a50375891a69"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select3"",
                    ""id"": ""82017b85-3f8f-4ee6-a860-e0a49d78f85c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select4"",
                    ""id"": ""8b7a484b-6192-48ad-a494-88c22e8c0066"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select5"",
                    ""id"": ""a61cda0d-b3fd-4f79-90e4-4231c0ca0ca8"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select6"",
                    ""id"": ""f805dfe0-7749-44da-b624-c22a98738c64"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select7"",
                    ""id"": ""2eded8a4-80e5-4b93-83d9-acc2d2baf8b8"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""select8"",
                    ""id"": ""532d0724-56a1-4247-8469-be78b275c2a9"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bb5ea9dd-f755-4da1-99c4-024f41793ee3"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHotBar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e6467d1-12db-4901-93df-eb714c6bbed4"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""BlockDelete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c85fb7f-2f33-4d90-85b5-1d0a0e84a185"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""AllCraft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f46df6d-d6f6-4384-9c48-2728241e9222"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""OneStackCraft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86ff9c27-2e02-4f71-94ab-8b2e5127f970"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuestUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b0c3c9e-4a0e-4275-ab26-32682c2ed4cc"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""ItemDirectMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11e79b02-c0f8-4a03-b1eb-fbee55d3f172"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""BlockPlace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Xbox Controller"",
            ""bindingGroup"": ""Xbox Controller"",
            ""devices"": []
        },
        {
            ""name"": ""PS4 Controller"",
            ""bindingGroup"": ""PS4 Controller"",
            ""devices"": []
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        // Playable
        m_Playable = asset.FindActionMap("Playable", throwIfNotFound: true);
        m_Playable_ScreenLeftClick = m_Playable.FindAction("ScreenLeftClick", throwIfNotFound: true);
        m_Playable_ScreenRightClick = m_Playable.FindAction("ScreenRightClick", throwIfNotFound: true);
        m_Playable_ClickPosition = m_Playable.FindAction("ClickPosition", throwIfNotFound: true);
        m_Playable_BlockPlaceRotation = m_Playable.FindAction("BlockPlaceRotation", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_OpenMenu = m_UI.FindAction("OpenMenu", throwIfNotFound: true);
        m_UI_CloseUI = m_UI.FindAction("CloseUI", throwIfNotFound: true);
        m_UI_OpenInventory = m_UI.FindAction("OpenInventory", throwIfNotFound: true);
        m_UI_InventoryItemOnePut = m_UI.FindAction("InventoryItemOnePut", throwIfNotFound: true);
        m_UI_InventoryItemHalve = m_UI.FindAction("InventoryItemHalve", throwIfNotFound: true);
        m_UI_HotBar = m_UI.FindAction("HotBar", throwIfNotFound: true);
        m_UI_SwitchHotBar = m_UI.FindAction("SwitchHotBar", throwIfNotFound: true);
        m_UI_BlockDelete = m_UI.FindAction("BlockDelete", throwIfNotFound: true);
        m_UI_BlockPlace = m_UI.FindAction("BlockPlace", throwIfNotFound: true);
        m_UI_AllCraft = m_UI.FindAction("AllCraft", throwIfNotFound: true);
        m_UI_OneStackCraft = m_UI.FindAction("OneStackCraft", throwIfNotFound: true);
        m_UI_QuestUI = m_UI.FindAction("QuestUI", throwIfNotFound: true);
        m_UI_ItemDirectMove = m_UI.FindAction("ItemDirectMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Sprint;
    public struct PlayerActions
    {
        private @MoorestechInputSettings m_Wrapper;
        public PlayerActions(@MoorestechInputSettings wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Playable
    private readonly InputActionMap m_Playable;
    private List<IPlayableActions> m_PlayableActionsCallbackInterfaces = new List<IPlayableActions>();
    private readonly InputAction m_Playable_ScreenLeftClick;
    private readonly InputAction m_Playable_ScreenRightClick;
    private readonly InputAction m_Playable_ClickPosition;
    private readonly InputAction m_Playable_BlockPlaceRotation;
    public struct PlayableActions
    {
        private @MoorestechInputSettings m_Wrapper;
        public PlayableActions(@MoorestechInputSettings wrapper) { m_Wrapper = wrapper; }
        public InputAction @ScreenLeftClick => m_Wrapper.m_Playable_ScreenLeftClick;
        public InputAction @ScreenRightClick => m_Wrapper.m_Playable_ScreenRightClick;
        public InputAction @ClickPosition => m_Wrapper.m_Playable_ClickPosition;
        public InputAction @BlockPlaceRotation => m_Wrapper.m_Playable_BlockPlaceRotation;
        public InputActionMap Get() { return m_Wrapper.m_Playable; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayableActions set) { return set.Get(); }
        public void AddCallbacks(IPlayableActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayableActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayableActionsCallbackInterfaces.Add(instance);
            @ScreenLeftClick.started += instance.OnScreenLeftClick;
            @ScreenLeftClick.performed += instance.OnScreenLeftClick;
            @ScreenLeftClick.canceled += instance.OnScreenLeftClick;
            @ScreenRightClick.started += instance.OnScreenRightClick;
            @ScreenRightClick.performed += instance.OnScreenRightClick;
            @ScreenRightClick.canceled += instance.OnScreenRightClick;
            @ClickPosition.started += instance.OnClickPosition;
            @ClickPosition.performed += instance.OnClickPosition;
            @ClickPosition.canceled += instance.OnClickPosition;
            @BlockPlaceRotation.started += instance.OnBlockPlaceRotation;
            @BlockPlaceRotation.performed += instance.OnBlockPlaceRotation;
            @BlockPlaceRotation.canceled += instance.OnBlockPlaceRotation;
        }

        private void UnregisterCallbacks(IPlayableActions instance)
        {
            @ScreenLeftClick.started -= instance.OnScreenLeftClick;
            @ScreenLeftClick.performed -= instance.OnScreenLeftClick;
            @ScreenLeftClick.canceled -= instance.OnScreenLeftClick;
            @ScreenRightClick.started -= instance.OnScreenRightClick;
            @ScreenRightClick.performed -= instance.OnScreenRightClick;
            @ScreenRightClick.canceled -= instance.OnScreenRightClick;
            @ClickPosition.started -= instance.OnClickPosition;
            @ClickPosition.performed -= instance.OnClickPosition;
            @ClickPosition.canceled -= instance.OnClickPosition;
            @BlockPlaceRotation.started -= instance.OnBlockPlaceRotation;
            @BlockPlaceRotation.performed -= instance.OnBlockPlaceRotation;
            @BlockPlaceRotation.canceled -= instance.OnBlockPlaceRotation;
        }

        public void RemoveCallbacks(IPlayableActions instance)
        {
            if (m_Wrapper.m_PlayableActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayableActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayableActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayableActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayableActions @Playable => new PlayableActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_OpenMenu;
    private readonly InputAction m_UI_CloseUI;
    private readonly InputAction m_UI_OpenInventory;
    private readonly InputAction m_UI_InventoryItemOnePut;
    private readonly InputAction m_UI_InventoryItemHalve;
    private readonly InputAction m_UI_HotBar;
    private readonly InputAction m_UI_SwitchHotBar;
    private readonly InputAction m_UI_BlockDelete;
    private readonly InputAction m_UI_BlockPlace;
    private readonly InputAction m_UI_AllCraft;
    private readonly InputAction m_UI_OneStackCraft;
    private readonly InputAction m_UI_QuestUI;
    private readonly InputAction m_UI_ItemDirectMove;
    public struct UIActions
    {
        private @MoorestechInputSettings m_Wrapper;
        public UIActions(@MoorestechInputSettings wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenMenu => m_Wrapper.m_UI_OpenMenu;
        public InputAction @CloseUI => m_Wrapper.m_UI_CloseUI;
        public InputAction @OpenInventory => m_Wrapper.m_UI_OpenInventory;
        public InputAction @InventoryItemOnePut => m_Wrapper.m_UI_InventoryItemOnePut;
        public InputAction @InventoryItemHalve => m_Wrapper.m_UI_InventoryItemHalve;
        public InputAction @HotBar => m_Wrapper.m_UI_HotBar;
        public InputAction @SwitchHotBar => m_Wrapper.m_UI_SwitchHotBar;
        public InputAction @BlockDelete => m_Wrapper.m_UI_BlockDelete;
        public InputAction @BlockPlace => m_Wrapper.m_UI_BlockPlace;
        public InputAction @AllCraft => m_Wrapper.m_UI_AllCraft;
        public InputAction @OneStackCraft => m_Wrapper.m_UI_OneStackCraft;
        public InputAction @QuestUI => m_Wrapper.m_UI_QuestUI;
        public InputAction @ItemDirectMove => m_Wrapper.m_UI_ItemDirectMove;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @OpenMenu.started += instance.OnOpenMenu;
            @OpenMenu.performed += instance.OnOpenMenu;
            @OpenMenu.canceled += instance.OnOpenMenu;
            @CloseUI.started += instance.OnCloseUI;
            @CloseUI.performed += instance.OnCloseUI;
            @CloseUI.canceled += instance.OnCloseUI;
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
            @InventoryItemOnePut.started += instance.OnInventoryItemOnePut;
            @InventoryItemOnePut.performed += instance.OnInventoryItemOnePut;
            @InventoryItemOnePut.canceled += instance.OnInventoryItemOnePut;
            @InventoryItemHalve.started += instance.OnInventoryItemHalve;
            @InventoryItemHalve.performed += instance.OnInventoryItemHalve;
            @InventoryItemHalve.canceled += instance.OnInventoryItemHalve;
            @HotBar.started += instance.OnHotBar;
            @HotBar.performed += instance.OnHotBar;
            @HotBar.canceled += instance.OnHotBar;
            @SwitchHotBar.started += instance.OnSwitchHotBar;
            @SwitchHotBar.performed += instance.OnSwitchHotBar;
            @SwitchHotBar.canceled += instance.OnSwitchHotBar;
            @BlockDelete.started += instance.OnBlockDelete;
            @BlockDelete.performed += instance.OnBlockDelete;
            @BlockDelete.canceled += instance.OnBlockDelete;
            @BlockPlace.started += instance.OnBlockPlace;
            @BlockPlace.performed += instance.OnBlockPlace;
            @BlockPlace.canceled += instance.OnBlockPlace;
            @AllCraft.started += instance.OnAllCraft;
            @AllCraft.performed += instance.OnAllCraft;
            @AllCraft.canceled += instance.OnAllCraft;
            @OneStackCraft.started += instance.OnOneStackCraft;
            @OneStackCraft.performed += instance.OnOneStackCraft;
            @OneStackCraft.canceled += instance.OnOneStackCraft;
            @QuestUI.started += instance.OnQuestUI;
            @QuestUI.performed += instance.OnQuestUI;
            @QuestUI.canceled += instance.OnQuestUI;
            @ItemDirectMove.started += instance.OnItemDirectMove;
            @ItemDirectMove.performed += instance.OnItemDirectMove;
            @ItemDirectMove.canceled += instance.OnItemDirectMove;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @OpenMenu.started -= instance.OnOpenMenu;
            @OpenMenu.performed -= instance.OnOpenMenu;
            @OpenMenu.canceled -= instance.OnOpenMenu;
            @CloseUI.started -= instance.OnCloseUI;
            @CloseUI.performed -= instance.OnCloseUI;
            @CloseUI.canceled -= instance.OnCloseUI;
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
            @InventoryItemOnePut.started -= instance.OnInventoryItemOnePut;
            @InventoryItemOnePut.performed -= instance.OnInventoryItemOnePut;
            @InventoryItemOnePut.canceled -= instance.OnInventoryItemOnePut;
            @InventoryItemHalve.started -= instance.OnInventoryItemHalve;
            @InventoryItemHalve.performed -= instance.OnInventoryItemHalve;
            @InventoryItemHalve.canceled -= instance.OnInventoryItemHalve;
            @HotBar.started -= instance.OnHotBar;
            @HotBar.performed -= instance.OnHotBar;
            @HotBar.canceled -= instance.OnHotBar;
            @SwitchHotBar.started -= instance.OnSwitchHotBar;
            @SwitchHotBar.performed -= instance.OnSwitchHotBar;
            @SwitchHotBar.canceled -= instance.OnSwitchHotBar;
            @BlockDelete.started -= instance.OnBlockDelete;
            @BlockDelete.performed -= instance.OnBlockDelete;
            @BlockDelete.canceled -= instance.OnBlockDelete;
            @BlockPlace.started -= instance.OnBlockPlace;
            @BlockPlace.performed -= instance.OnBlockPlace;
            @BlockPlace.canceled -= instance.OnBlockPlace;
            @AllCraft.started -= instance.OnAllCraft;
            @AllCraft.performed -= instance.OnAllCraft;
            @AllCraft.canceled -= instance.OnAllCraft;
            @OneStackCraft.started -= instance.OnOneStackCraft;
            @OneStackCraft.performed -= instance.OnOneStackCraft;
            @OneStackCraft.canceled -= instance.OnOneStackCraft;
            @QuestUI.started -= instance.OnQuestUI;
            @QuestUI.performed -= instance.OnQuestUI;
            @QuestUI.canceled -= instance.OnQuestUI;
            @ItemDirectMove.started -= instance.OnItemDirectMove;
            @ItemDirectMove.performed -= instance.OnItemDirectMove;
            @ItemDirectMove.canceled -= instance.OnItemDirectMove;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_XboxControllerSchemeIndex = -1;
    public InputControlScheme XboxControllerScheme
    {
        get
        {
            if (m_XboxControllerSchemeIndex == -1) m_XboxControllerSchemeIndex = asset.FindControlSchemeIndex("Xbox Controller");
            return asset.controlSchemes[m_XboxControllerSchemeIndex];
        }
    }
    private int m_PS4ControllerSchemeIndex = -1;
    public InputControlScheme PS4ControllerScheme
    {
        get
        {
            if (m_PS4ControllerSchemeIndex == -1) m_PS4ControllerSchemeIndex = asset.FindControlSchemeIndex("PS4 Controller");
            return asset.controlSchemes[m_PS4ControllerSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
    }
    public interface IPlayableActions
    {
        void OnScreenLeftClick(InputAction.CallbackContext context);
        void OnScreenRightClick(InputAction.CallbackContext context);
        void OnClickPosition(InputAction.CallbackContext context);
        void OnBlockPlaceRotation(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnOpenMenu(InputAction.CallbackContext context);
        void OnCloseUI(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnInventoryItemOnePut(InputAction.CallbackContext context);
        void OnInventoryItemHalve(InputAction.CallbackContext context);
        void OnHotBar(InputAction.CallbackContext context);
        void OnSwitchHotBar(InputAction.CallbackContext context);
        void OnBlockDelete(InputAction.CallbackContext context);
        void OnBlockPlace(InputAction.CallbackContext context);
        void OnAllCraft(InputAction.CallbackContext context);
        void OnOneStackCraft(InputAction.CallbackContext context);
        void OnQuestUI(InputAction.CallbackContext context);
        void OnItemDirectMove(InputAction.CallbackContext context);
    }
}
