using Mono.Cecil;

namespace DeadMemberAudit.Metadata;

// PDBのシーケンスポイントからメンバーのソース位置を引き、生成コードかどうかも判定する
// Reads a member's source location from PDB sequence points and decides whether it is generated code
public sealed class SourceLocator
{
    private readonly string _repositoryRoot;
    private readonly Dictionary<string, bool> _generatedFileCache = new(StringComparer.Ordinal);

    public SourceLocator(string repositoryRoot)
    {
        _repositoryRoot = repositoryRoot;
    }

    // 実ファイルが無いパスはSourceGeneratorの仮想ファイル。あるならヘッダの<auto-generated>を見る
    // A path with no real file is a source generator's virtual file; if it exists, check the <auto-generated> header
    public bool IsGeneratedSource(MethodDefinition method)
    {
        var path = DocumentPath(method);
        if (path == null) return false;
        if (_generatedFileCache.TryGetValue(path, out var cached)) return cached;

        var isGenerated = !File.Exists(path) || HasAutoGeneratedHeader(path);
        _generatedFileCache[path] = isGenerated;
        return isGenerated;
    }

    // レポート用の相対パス。シーケンスポイントが無ければ空文字を返す
    // Relative path for the report; returns an empty string when there is no sequence point
    public string DisplayLocation(MethodDefinition method)
    {
        var point = FirstSequencePoint(method);
        if (point == null) return string.Empty;

        var path = point.Document.Url;
        if (!File.Exists(path)) return string.Empty;
        var relative = Path.GetRelativePath(_repositoryRoot, path);
        return $"{relative}:{point.StartLine}";
    }

    // 特定の命令の位置。async本体は生成メソッドへ移るが、シーケンスポイントは元のソース行を指したまま
    // Location of one instruction; an async body moves into a generated method yet its sequence points still point at the original source
    public string LocationOf(MethodDefinition method, Mono.Cecil.Cil.Instruction instruction)
    {
        if (!method.HasBody || method.DebugInformation == null || !method.DebugInformation.HasSequencePoints) return string.Empty;

        Mono.Cecil.Cil.SequencePoint? nearest = null;
        foreach (var point in method.DebugInformation.SequencePoints)
        {
            if (point.IsHidden || point.Offset > instruction.Offset) continue;
            if (nearest == null || point.Offset > nearest.Offset) nearest = point;
        }

        if (nearest == null || !File.Exists(nearest.Document.Url)) return string.Empty;
        return $"{Path.GetRelativePath(_repositoryRoot, nearest.Document.Url)}:{nearest.StartLine}";
    }

    private static string? DocumentPath(MethodDefinition method)
    {
        return FirstSequencePoint(method)?.Document.Url;
    }

    private static Mono.Cecil.Cil.SequencePoint? FirstSequencePoint(MethodDefinition method)
    {
        if (!method.HasBody || method.DebugInformation == null || !method.DebugInformation.HasSequencePoints) return null;

        // 隠しシーケンスポイント(0xFEEFEE)は行番号がダミーなので採用しない
        // A hidden sequence point (0xFEEFEE) carries a dummy line number, so it is not used
        return method.DebugInformation.SequencePoints.FirstOrDefault(point => !point.IsHidden);
    }

    // ヘッダ数行だけ読めば判定できる。Unity生成のinputactionsラッパー等がこれに当たる
    // A few header lines are enough; Unity's generated inputactions wrapper is one such file
    private static bool HasAutoGeneratedHeader(string path)
    {
        // ファイル読み込みは外部境界。生成判定のためだけなので失敗時は生成物でないとみなす
        // Reading a file is an external boundary; on failure it is simply treated as not generated
        try
        {
            return File.ReadLines(path).Take(10).Any(line => line.Contains("<auto-generated", StringComparison.Ordinal));
        }
        catch (IOException)
        {
            return false;
        }
    }
}
