using System;
using System.Collections.Generic;
using Client.Common;
using Client.Game.InGame.Map.MapObject;
using NUnit.Framework;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEngine;

namespace Client.Tests.Map
{
    /// <summary>
    ///     全speciesの登録先と採掘構造を検証
    ///     Verifies every species' Addressable registration and mining structure
    /// </summary>
    // ラッパーはgitignoreされたPersonalAssetsのBKプレハブのバリアントで、CIには親が無く必ずnullになる
    // The wrappers are variants of BK prefabs under the gitignored PersonalAssets, whose parents never exist on CI
    [Category("IgnoreCI")]
    public class MapObjectAddressableLoadTest
    {
        // 今回生成する樹種・岩のアドレス空間。既存のVanilla/Environment/Tree(スラッシュ無し)とは前方一致で衝突しない
        // The address space generated by this task; it never prefix-collides with the existing slash-less Vanilla/Environment/Tree
        private static readonly string[] GeneratedAddressPrefixes = { "Vanilla/Environment/Tree/", "Vanilla/Environment/Rock/" };

        [Test]
        public void インベントリ全species分のラッパープレハブがアドレスから引ける()
        {
            var species = MapObjectWrapperInventory.LoadSpecies();
            var assetPathByAddress = CollectAddressableAssetPaths();

            foreach (var element in species)
            {
                Assert.IsTrue(assetPathByAddress.TryGetValue(element.address, out var registeredAssetPath), $"address is not registered to Addressables: {element.address}");
                Assert.AreEqual(element.wrapperPath, registeredAssetPath, $"address points at an unexpected asset: {element.address}");

                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(element.wrapperPath);
                Assert.IsNotNull(prefab, $"wrapper prefab does not exist: {element.wrapperPath}");

                // ルート直下のMapObjectGameObjectが採掘・HP表示の起点。子に降りていると生成側が見つけられない
                // MapObjectGameObject on the root is where mining and the HP bar start; nested under a child it would never be found
                var mapObject = prefab.GetComponent<MapObjectGameObject>();
                Assert.IsNotNull(mapObject, $"root has no MapObjectGameObject: {element.wrapperPath}");
                Assert.IsNotNull(prefab.GetComponentInChildren<MapObjectRayTarget>(true), $"no MapObjectRayTarget for the mining raycast: {element.wrapperPath}");

                var serializedMapObject = new SerializedObject(mapObject);
                var outlineObject = serializedMapObject.FindProperty("outlineObject").objectReferenceValue as GameObject;
                var hpBarView = serializedMapObject.FindProperty("hpBarView").objectReferenceValue as MapObjectHpBarView;
                var mapObjectGuid = serializedMapObject.FindProperty("mapObjectGuid").stringValue;
                Assert.IsNotNull(outlineObject, $"outlineObject is not wired: {element.wrapperPath}");
                Assert.AreEqual(element.mapObjectGuid, mapObjectGuid, $"mapObjectGuid does not match the inventory: {element.wrapperPath}");

                // PickUp種(小石)は既存Pebble.prefab前例に倣いHPバーを持たない
                // PickUp species (pebbles) carry no HP bar, matching the existing Pebble.prefab precedent
                if (element.kind == "pebble")
                {
                    Assert.IsNull(hpBarView, $"pebble species must not have a hp bar: {element.wrapperPath}");
                }
                else
                {
                    Assert.IsNotNull(hpBarView, $"hpBarView is not wired: {element.wrapperPath}");

                    // HPバーの高さ(localBounds.max.y)はルートローカル空間の値なので、ルート直下に置いてそのまま渡している
                    // The HP bar height (localBounds.max.y) is expressed in the root's local space, so it sits directly under the root to consume that value as-is
                    Assert.AreSame(prefab.transform, hpBarView.transform.parent, $"hp bar is not a direct child of the root: {element.wrapperPath}");
                }

                // BK由来の当たり判定がDefaultレイヤーに残ると設置レイが樹木に刺さる
                // A BK collider left on the Default layer would make the block placement ray hit the tree
                foreach (var collider in prefab.GetComponentsInChildren<Collider>(true))
                    Assert.AreEqual(LayerConst.MapObjectLayer, collider.gameObject.layer, $"collider {collider.name} is not on the MapObject layer: {element.wrapperPath}");
            }
        }

        [Test]
        public void 生成対象外のアドレスが樹種岩の空間に混ざっていない()
        {
            var species = MapObjectWrapperInventory.LoadSpecies();
            var inventoryAddresses = new HashSet<string>();
            foreach (var element in species) inventoryAddresses.Add(element.address);

            foreach (var registered in CollectAddressableAssetPaths())
            {
                if (!HasGeneratedPrefix(registered.Key)) continue;
                Assert.IsTrue(inventoryAddresses.Contains(registered.Key), $"stale address left in the generated address space: {registered.Key}");
            }

            #region Internal

            bool HasGeneratedPrefix(string address)
            {
                foreach (var prefix in GeneratedAddressPrefixes)
                    if (address.StartsWith(prefix, StringComparison.Ordinal))
                        return true;
                return false;
            }

            #endregion
        }

        private static Dictionary<string, string> CollectAddressableAssetPaths()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            Assert.IsNotNull(settings, "AddressableAssetSettings is missing");

            var assetPathByAddress = new Dictionary<string, string>();
            foreach (var group in settings.groups)
            {
                if (group == null) continue;
                foreach (var entry in group.entries) assetPathByAddress[entry.address] = AssetDatabase.GUIDToAssetPath(entry.guid);
            }

            return assetPathByAddress;
        }
    }
}
