using System;
using System.Collections.Generic;
using System.IO;
using Client.Common;
using Client.Game.InGame.Map.MapObject;
using NUnit.Framework;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEngine;

namespace Client.Tests.Map
{
    /// <summary>
    ///     BK樹種・岩のラッパープレハブがインベントリ全件分ぶんAddressableへ登録され、採掘に必要な構造を備えていることを検証する
    ///     Verifies every species in the inventory has a wrapper prefab registered to Addressables with the structure mining requires
    /// </summary>
    public class MapObjectAddressableLoadTest
    {
        // 今回生成する樹種・岩のアドレス空間。既存のVanilla/Environment/Tree(スラッシュ無し)とは前方一致で衝突しない
        // The address space generated by this task; it never prefix-collides with the existing slash-less Vanilla/Environment/Tree
        private static readonly string[] GeneratedAddressPrefixes = { "Vanilla/Environment/Tree/", "Vanilla/Environment/Rock/" };

        // 採掘可能距離(MiningController.miningDistance=2.5)とカメラの背後距離(PlayerSystem.prefabのm_CameraDistance=3.5)
        // The mining reach (MiningController.miningDistance = 2.5) and the camera's follow distance (PlayerSystem.prefab m_CameraDistance = 3.5)
        private const float MiningDistance = 2.5f;
        private const float CameraDistance = 3.5f;

        [Test]
        public void インベントリ全species分のラッパープレハブがアドレスから引ける()
        {
            var species = LoadInventorySpecies();
            Assert.IsNotEmpty(species, "species inventory is empty; the test would pass vacuously");

            var assetPathByAddress = CollectAddressableAssetPaths();

            foreach (var element in species)
            {
                Assert.IsTrue(assetPathByAddress.TryGetValue(element.address, out var registeredAssetPath), $"address is not registered to Addressables: {element.address}");
                Assert.AreEqual(element.wrapperPath, registeredAssetPath, $"address points at an unexpected asset: {element.address}");

                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(element.wrapperPath);
                Assert.IsNotNull(prefab, $"wrapper prefab does not exist: {element.wrapperPath}");

                // ルート直下のMapObjectGameObjectが採掘・HP表示の起点。子に降りていると生成側が見つけられない
                // MapObjectGameObject on the root is where mining and the HP bar start; nested under a child it would never be found
                var mapObject = prefab.GetComponent<MapObjectGameObject>();
                Assert.IsNotNull(mapObject, $"root has no MapObjectGameObject: {element.wrapperPath}");
                Assert.IsNotNull(prefab.GetComponentInChildren<MapObjectRayTarget>(true), $"no MapObjectRayTarget for the mining raycast: {element.wrapperPath}");

                var serializedMapObject = new SerializedObject(mapObject);
                var outlineObject = serializedMapObject.FindProperty("outlineObject").objectReferenceValue as GameObject;
                var hpBarView = serializedMapObject.FindProperty("hpBarView").objectReferenceValue as MapObjectHpBarView;
                Assert.IsNotNull(outlineObject, $"outlineObject is not wired: {element.wrapperPath}");
                Assert.IsNotNull(hpBarView, $"hpBarView is not wired: {element.wrapperPath}");

                // HPバーの逆スケール補正が親のlossyScaleを読むため、ルート直下でなければ補正が別物になる
                // The HP bar counter-scale reads its parent lossyScale, so anywhere but directly under the root changes what it corrects
                Assert.AreSame(prefab.transform, hpBarView.transform.parent, $"hp bar is not a direct child of the root: {element.wrapperPath}");

                // BK由来の当たり判定がDefaultレイヤーに残ると設置レイが樹木に刺さる
                // A BK collider left on the Default layer would make the block placement ray hit the tree
                foreach (var collider in prefab.GetComponentsInChildren<Collider>(true))
                    Assert.AreEqual(LayerConst.MapObjectLayer, collider.gameObject.layer, $"collider {collider.name} is not on the MapObject layer: {element.wrapperPath}");
            }
        }

        [Test]
        public void レイターゲットが採掘レンジのカメラを内側に飲み込まない()
        {
            var species = LoadInventorySpecies();
            Assert.IsNotEmpty(species, "species inventory is empty; the test would pass vacuously");

            // カメラがコライダー内部に入るとUnityはそのコライダーへレイを当てないため、採掘レンジで届く距離より太いレイターゲットは採掘不能になる
            // Unity never hits a collider from inside it, so a ray target wider than the camera can get is impossible to mine
            var allowedHorizontalRadius = MiningDistance + CameraDistance;

            foreach (var element in species)
            {
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(element.wrapperPath);
                Assert.IsNotNull(prefab, $"wrapper prefab does not exist: {element.wrapperPath}");

                var rayTarget = prefab.GetComponentInChildren<MapObjectRayTarget>(true);
                Assert.IsNotNull(rayTarget, $"no MapObjectRayTarget for the mining raycast: {element.wrapperPath}");

                // 前例(AddressableResources/Environment/Tree.prefab)と同じく幹に沿ったconvex MeshColliderであること
                // Same shape as the precedent (AddressableResources/Environment/Tree.prefab): a convex MeshCollider hugging the trunk
                var meshCollider = rayTarget.GetComponent<Collider>() as MeshCollider;
                Assert.IsNotNull(meshCollider, $"ray target collider is not a MeshCollider: {element.wrapperPath}");
                Assert.IsTrue(meshCollider.convex, $"ray target MeshCollider is not convex: {element.wrapperPath}");
                Assert.IsTrue(meshCollider.isTrigger, $"ray target MeshCollider is not a trigger: {element.wrapperPath}");

                var horizontalRadius = CalculateHorizontalRadiusFromRoot(prefab.transform, meshCollider.transform, meshCollider.sharedMesh.bounds);
                Assert.LessOrEqual(horizontalRadius, allowedHorizontalRadius, $"ray target is wider than the mining camera can stand off, so it can never be hit: {element.wrapperPath}");
            }
        }

        [Test]
        public void 生成対象外のアドレスが樹種岩の空間に混ざっていない()
        {
            var species = LoadInventorySpecies();
            var inventoryAddresses = new HashSet<string>();
            foreach (var element in species) inventoryAddresses.Add(element.address);

            foreach (var registered in CollectAddressableAssetPaths())
            {
                if (!HasGeneratedPrefix(registered.Key)) continue;
                Assert.IsTrue(inventoryAddresses.Contains(registered.Key), $"stale address left in the generated address space: {registered.Key}");
            }

            #region Internal

            bool HasGeneratedPrefix(string address)
            {
                foreach (var prefix in GeneratedAddressPrefixes)
                    if (address.StartsWith(prefix, StringComparison.Ordinal))
                        return true;
                return false;
            }

            #endregion
        }

        // ルートの原点(=プレイヤーが近づく位置)からコライダー外周までの水平距離
        // Horizontal distance from the root origin, which is where the player walks up to, out to the collider's far side
        private static float CalculateHorizontalRadiusFromRoot(Transform root, Transform colliderTransform, Bounds colliderLocalBounds)
        {
            var toRootLocal = root.worldToLocalMatrix * colliderTransform.localToWorldMatrix;
            var radius = 0f;
            for (var cornerIndex = 0; cornerIndex < 8; cornerIndex++)
            {
                var corner = new Vector3(
                    (cornerIndex & 1) == 0 ? colliderLocalBounds.min.x : colliderLocalBounds.max.x,
                    (cornerIndex & 2) == 0 ? colliderLocalBounds.min.y : colliderLocalBounds.max.y,
                    (cornerIndex & 4) == 0 ? colliderLocalBounds.min.z : colliderLocalBounds.max.z);
                var rootLocal = toRootLocal.MultiplyPoint3x4(corner);
                radius = Mathf.Max(radius, new Vector2(rootLocal.x, rootLocal.z).magnitude);
            }

            return radius;
        }

        private static List<SpeciesElement> LoadInventorySpecies()
        {
            // 抽出スクリプトの出力がアドレスとラッパーパスの唯一のソース
            // The extraction script's output is the single source of addresses and wrapper paths
            var inventoryPath = Path.GetFullPath(Path.Combine(Application.dataPath, "../../scripts/mapmaking-parity/species-inventory.json"));
            Assert.IsTrue(File.Exists(inventoryPath), $"species inventory not found: {inventoryPath}");

            return JsonUtility.FromJson<SpeciesInventory>(File.ReadAllText(inventoryPath)).species;
        }

        private static Dictionary<string, string> CollectAddressableAssetPaths()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            Assert.IsNotNull(settings, "AddressableAssetSettings is missing");

            var assetPathByAddress = new Dictionary<string, string>();
            foreach (var group in settings.groups)
            {
                if (group == null) continue;
                foreach (var entry in group.entries) assetPathByAddress[entry.address] = AssetDatabase.GUIDToAssetPath(entry.guid);
            }

            return assetPathByAddress;
        }

        [Serializable]
        private class SpeciesInventory
        {
            public List<SpeciesElement> species;
        }

        [Serializable]
        private class SpeciesElement
        {
            public string address;
            public string wrapperPath;
        }
    }
}
