using System;
using System.Collections.Generic;
using System.IO;
using Client.Common;
using Client.Game.InGame.Map.MapObject;
using NUnit.Framework;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEngine;

namespace Client.Tests.Map
{
    /// <summary>
    ///     BK樹種・岩のラッパープレハブがインベントリ全件分ぶんAddressableへ登録され、採掘に必要な構造を備えていることを検証する
    ///     Verifies every species in the inventory has a wrapper prefab registered to Addressables with the structure mining requires
    /// </summary>
    public class MapObjectAddressableLoadTest
    {
        // 今回生成する樹種・岩のアドレス空間。既存のVanilla/Environment/Tree(スラッシュ無し)とは前方一致で衝突しない
        // The address space generated by this task; it never prefix-collides with the existing slash-less Vanilla/Environment/Tree
        private static readonly string[] GeneratedAddressPrefixes = { "Vanilla/Environment/Tree/", "Vanilla/Environment/Rock/" };

        [Test]
        public void インベントリ全species分のラッパープレハブがアドレスから引ける()
        {
            var species = LoadInventorySpecies();
            Assert.IsNotEmpty(species, "species inventory is empty; the test would pass vacuously");

            var assetPathByAddress = CollectAddressableAssetPaths();

            foreach (var element in species)
            {
                Assert.IsTrue(assetPathByAddress.TryGetValue(element.address, out var registeredAssetPath), $"address is not registered to Addressables: {element.address}");
                Assert.AreEqual(element.wrapperPath, registeredAssetPath, $"address points at an unexpected asset: {element.address}");

                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(element.wrapperPath);
                Assert.IsNotNull(prefab, $"wrapper prefab does not exist: {element.wrapperPath}");

                // ルート直下のMapObjectGameObjectが採掘・HP表示の起点。子に降りていると生成側が見つけられない
                // MapObjectGameObject on the root is where mining and the HP bar start; nested under a child it would never be found
                var mapObject = prefab.GetComponent<MapObjectGameObject>();
                Assert.IsNotNull(mapObject, $"root has no MapObjectGameObject: {element.wrapperPath}");
                Assert.IsNotNull(prefab.GetComponentInChildren<MapObjectRayTarget>(true), $"no MapObjectRayTarget for the mining raycast: {element.wrapperPath}");

                var serializedMapObject = new SerializedObject(mapObject);
                var outlineObject = serializedMapObject.FindProperty("outlineObject").objectReferenceValue as GameObject;
                var hpBarView = serializedMapObject.FindProperty("hpBarView").objectReferenceValue as MapObjectHpBarView;
                Assert.IsNotNull(outlineObject, $"outlineObject is not wired: {element.wrapperPath}");
                Assert.IsNotNull(hpBarView, $"hpBarView is not wired: {element.wrapperPath}");

                // HPバーの逆スケール補正が親のlossyScaleを読むため、ルート直下でなければ補正が別物になる
                // The HP bar counter-scale reads its parent lossyScale, so anywhere but directly under the root changes what it corrects
                Assert.AreSame(prefab.transform, hpBarView.transform.parent, $"hp bar is not a direct child of the root: {element.wrapperPath}");

                // BK由来の当たり判定がDefaultレイヤーに残ると設置レイが樹木に刺さる
                // A BK collider left on the Default layer would make the block placement ray hit the tree
                foreach (var collider in prefab.GetComponentsInChildren<Collider>(true))
                    Assert.AreEqual(LayerConst.MapObjectLayer, collider.gameObject.layer, $"collider {collider.name} is not on the MapObject layer: {element.wrapperPath}");
            }
        }

        [Test]
        public void 生成対象外のアドレスが樹種岩の空間に混ざっていない()
        {
            var species = LoadInventorySpecies();
            var inventoryAddresses = new HashSet<string>();
            foreach (var element in species) inventoryAddresses.Add(element.address);

            foreach (var registered in CollectAddressableAssetPaths())
            {
                if (!HasGeneratedPrefix(registered.Key)) continue;
                Assert.IsTrue(inventoryAddresses.Contains(registered.Key), $"stale address left in the generated address space: {registered.Key}");
            }

            #region Internal

            bool HasGeneratedPrefix(string address)
            {
                foreach (var prefix in GeneratedAddressPrefixes)
                    if (address.StartsWith(prefix, StringComparison.Ordinal))
                        return true;
                return false;
            }

            #endregion
        }

        private static List<SpeciesElement> LoadInventorySpecies()
        {
            // 抽出スクリプトの出力がアドレスとラッパーパスの唯一のソース
            // The extraction script's output is the single source of addresses and wrapper paths
            var inventoryPath = Path.GetFullPath(Path.Combine(Application.dataPath, "../../scripts/mapmaking-parity/species-inventory.json"));
            Assert.IsTrue(File.Exists(inventoryPath), $"species inventory not found: {inventoryPath}");

            return JsonUtility.FromJson<SpeciesInventory>(File.ReadAllText(inventoryPath)).species;
        }

        private static Dictionary<string, string> CollectAddressableAssetPaths()
        {
            var settings = AddressableAssetSettingsDefaultObject.Settings;
            Assert.IsNotNull(settings, "AddressableAssetSettings is missing");

            var assetPathByAddress = new Dictionary<string, string>();
            foreach (var group in settings.groups)
            {
                if (group == null) continue;
                foreach (var entry in group.entries) assetPathByAddress[entry.address] = AssetDatabase.GUIDToAssetPath(entry.guid);
            }

            return assetPathByAddress;
        }

        [Serializable]
        private class SpeciesInventory
        {
            public List<SpeciesElement> species;
        }

        [Serializable]
        private class SpeciesElement
        {
            public string address;
            public string wrapperPath;
        }
    }
}
