// Unity C#にはプライオリティーキューがないので自前実装する必要がある
// A priority queue is not available in Unity C#, so it needs to be implemented manually.
// generated by Chat GPT 4o
using System;
using System.Collections.Generic;

namespace Game.Train.RailGraph 
{ 
    public class PriorityQueue<TElement, TPriority> where TPriority : IComparable<TPriority>
    {
        private List<(TElement Element, TPriority Priority)> _heap = new();

        public int Count => _heap.Count;

        public void Enqueue(TElement element, TPriority priority)
        {
            _heap.Add((element, priority));
            HeapifyUp(_heap.Count - 1);
        }

        public TElement Dequeue()
        {
            if (_heap.Count == 0)
            {
                throw new InvalidOperationException("The priority queue is empty.");
            }

            TElement element = _heap[0].Element;
            _heap[0] = _heap[^1]; // Move the last element to the root
            _heap.RemoveAt(_heap.Count - 1);
            if (_heap.Count > 0)
            {
                HeapifyDown(0);
            }
            return element;
        }

        public TElement Peek()
        {
            if (_heap.Count == 0)
            {
                throw new InvalidOperationException("The priority queue is empty.");
            }
            return _heap[0].Element;
        }

        private void HeapifyUp(int index)
        {
            while (index > 0)
            {
                int parentIndex = (index - 1) / 2;
                if (_heap[index].Priority.CompareTo(_heap[parentIndex].Priority) >= 0)
                {
                    break;
                }
                Swap(index, parentIndex);
                index = parentIndex;
            }
        }

        private void HeapifyDown(int index)
        {
            while (index < _heap.Count)
            {
                int leftChildIndex = 2 * index + 1;
                int rightChildIndex = 2 * index + 2;
                int smallestIndex = index;

                if (leftChildIndex < _heap.Count && _heap[leftChildIndex].Priority.CompareTo(_heap[smallestIndex].Priority) < 0)
                {
                    smallestIndex = leftChildIndex;
                }

                if (rightChildIndex < _heap.Count && _heap[rightChildIndex].Priority.CompareTo(_heap[smallestIndex].Priority) < 0)
                {
                    smallestIndex = rightChildIndex;
                }

                if (smallestIndex == index)
                {
                    break;
                }

                Swap(index, smallestIndex);
                index = smallestIndex;
            }
        }

        private void Swap(int indexA, int indexB)
        {
            (_heap[indexA], _heap[indexB]) = (_heap[indexB], _heap[indexA]);
        }
    }




    // ダイクストラ法専用のプライオリティーキュー
    // Dijkstra's algorithm specific priority queue
    public sealed class DijkstraPriorityQueue
    {
        private readonly List<int> _heap = new();
        private readonly int[] _distances;
        private readonly int[] _stamp;
        private readonly Func<int> _getCurrentStamp;

        public int Count => _heap.Count;

        public DijkstraPriorityQueue(int[] distances, int[] stamp, Func<int> getCurrentStamp)
        {
            _distances = distances;
            _stamp = stamp;
            _getCurrentStamp = getCurrentStamp;
        }

        public void Clear()
        {
            _heap.Clear();
        }

        public void Enqueue(int nodeId)
        {
            _heap.Add(nodeId);
            HeapifyUp(_heap.Count - 1);
        }

        public int Dequeue()
        {
            if (_heap.Count == 0)
                throw new InvalidOperationException("The priority queue is empty.");

            int result = _heap[0];
            _heap[0] = _heap[^1];
            _heap.RemoveAt(_heap.Count - 1);
            if (_heap.Count > 0)
                HeapifyDown(0);
            return result;
        }

        // ---------------- 内部 ----------------

        private int CurrentStamp => _getCurrentStamp();

        // stamp 未更新なら距離は「無限（MaxValue）」扱い
        private int GetDistance(int nodeId)
        {
            return _stamp[nodeId] == CurrentStamp ? _distances[nodeId] : int.MaxValue;
        }

        // 「距離 → nodeId」の順で比較
        private bool Less(int nodeA, int nodeB)
        {
            int da = GetDistance(nodeA);
            int db = GetDistance(nodeB);
            if (da != db) return da < db;
            return nodeA < nodeB; // tie-breaker: nodeId が小さい方
        }

        private void HeapifyUp(int index)
        {
            while (index > 0)
            {
                int parentIndex = (index - 1) / 2;
                if (!Less(_heap[index], _heap[parentIndex]))
                    break;
                Swap(index, parentIndex);
                index = parentIndex;
            }
        }

        private void HeapifyDown(int index)
        {
            int count = _heap.Count;
            while (true)
            {
                int left = 2 * index + 1;
                int right = 2 * index + 2;
                int smallest = index;

                if (left < count && Less(_heap[left], _heap[smallest]))
                    smallest = left;
                if (right < count && Less(_heap[right], _heap[smallest]))
                    smallest = right;

                if (smallest == index)
                    break;

                Swap(index, smallest);
                index = smallest;
            }
        }

        private void Swap(int a, int b)
        {
            (_heap[a], _heap[b]) = (_heap[b], _heap[a]);
        }
    }

}