id: mapObjectMineSettings
type: array
overrideCodeGeneratePropertyName: MapObjectMineSettingsMasterElement
items:
  type: object
  properties:
    - key: mapObjectGuid
      type: uuid
      foreignKey:
        schemaId: map
        foreignKeyIdPath: /mapObjects/[*]/mapObjectGuid
        displayElementPath: /mapObjects/[*]/mapObjectName
    - key: miningTime
      type: number
      default: 1
    - key: attackHp
      type: integer
      default: 1
