using System.Collections.Generic;
using Client.Game.InGame.Environment.Terrain;
using NUnit.Framework;
using UnityEngine;

namespace Client.Tests.Map.Surface
{
#if UNITY_EDITOR
    internal static class SurfaceAssetContractInputs
    {
        public static Dictionary<string, string> CollectAddressablePaths()
        {
            var settings = UnityEditor.AddressableAssets.AddressableAssetSettingsDefaultObject.Settings;
            Assert.That(settings, Is.Not.Null);
            var result = new Dictionary<string, string>();
            foreach (var group in settings.groups)
            {
                if (group == null) continue;
                foreach (var entry in group.entries)
                    result[entry.address] = UnityEditor.AssetDatabase.GUIDToAssetPath(entry.guid);
            }
            return result;
        }

        public static GameObject LoadPrefab(string path)
        {
            return UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(path);
        }

        public static void AssertWaterInputs()
        {
            // 水shaderは非公開アセット。取り込まれていない環境では入力契約を判定できない
            // The water shader is a private asset; without it imported the input contract cannot be judged
            var shader = Shader.Find("BK/Water");
            if (shader == null) Assert.Inconclusive("BK/Water shader is not imported in this checkout.");
            Assert.That(shader.FindPropertyIndex("_WavesHeight"), Is.Not.EqualTo(-1), "BK/Water must expose _WavesHeight");

            var prefab = LoadPrefab("Assets/Asset/Common/Prefab/Environment/AutoGenerated.prefab");
            Assert.That(prefab, Is.Not.Null);
            var ocean = prefab.GetComponentInChildren<GeneratedOceanSurface>(true);
            Assert.That(ocean, Is.Not.Null, "Generated ocean controller must be wired");
            var serialized = new UnityEditor.SerializedObject(ocean);
            var wiredProperty = serialized.FindProperty("waterRenderers");
            var wired = new HashSet<Renderer>();
            for (var index = 0; index < wiredProperty.arraySize; index++)
            {
                var renderer = wiredProperty.GetArrayElementAtIndex(index).objectReferenceValue as Renderer;
                Assert.That(renderer, Is.Not.Null, "Every wired renderer must exist");
                Assert.That(wired.Add(renderer), Is.True, "Water renderer wiring must be distinct");
            }
            var waterCount = 0;
            foreach (var renderer in prefab.GetComponentsInChildren<Renderer>(true))
            {
                var material = renderer.sharedMaterial;
                if (material == null || material.shader.name != "BK/Water") continue;
                waterCount++;
                Assert.That(wired.Contains(renderer), Is.True, renderer.name + " must be wired");
                Assert.That(material.HasProperty("_WavesHeight"), Is.True);
                Assert.That(material.GetFloat("_WavesHeight"), Is.InRange(0f, 0.5f));

                // shaderはobject法線を世界変位として使う
                // The shader uses object normals as world displacement vectors
                var filter = renderer.GetComponent<MeshFilter>();
                Assert.That(filter, Is.Not.Null);
                Assert.That(filter.sharedMesh, Is.Not.Null);
                foreach (var normal in filter.sharedMesh.normals)
                    Assert.That((normal - Vector3.up).sqrMagnitude, Is.LessThan(0.000001f));
                foreach (var vertex in filter.sharedMesh.vertices)
                    Assert.That(Mathf.Abs(renderer.transform.TransformVector(vertex).y), Is.LessThan(0.0001f));
            }
            Assert.That(waterCount, Is.GreaterThan(0));
            Assert.That(wired.Count, Is.EqualTo(waterCount), "All wired renderers must use the water shader");
        }
    }
#endif
}
